name: ci

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: voidzero-dev/setup-vp@v1
              with:
                  node-version: "lts"
            - run: vp install
            - run: vp run build
            - run: vp check
            - run: vp run test
            - run: vp run typecheck

    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: voidzero-dev/setup-vp@v1
              with:
                  node-version: "lts"
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.3.8
            - run: vp install
            - run: bun run extract-static/scripts/compile.ts
            - run: ls -la extract-static/prebuilts
